apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80        # External port for the service
    targetPort: 5000 # Port exposed by the container
  type: LoadBalancer